import CustomError from './CustomError';
export default class RetryAfterError extends CustomError {
    private readonly _retryAt;
    constructor(after: number);
    readonly retryAt: number;
}
